SHELL := /bin/bash

grpc-dep:
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

protoc-nomal:
	protoc ./business/greetpb/greet.proto --go-grpc_out=.

protoc-relative:
	protoc ./business/greetpb/greet.proto --go-grpc_out=. --go-grpc_opt=paths=source_relative

protoc-full:
	protoc ./business/greetpb/greet.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative